# Generated by Django 4.2.5 on 2023-10-04 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatting',
            old_name='guest',
            new_name='recipient',
        ),
    ]
