# Generated by Django 4.2.5 on 2023-10-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0003_guestuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatting',
            name='recipient',
        ),
    ]
