# Generated by Django 4.2.6 on 2023-10-05 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0005_remove_chatting_user_chatting_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='guest_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chatbox.guestuser'),
        ),
        migrations.AlterField(
            model_name='chatting',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
