# Generated by Django 4.2.6 on 2023-10-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbox', '0008_remove_chatting_guest_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestuser',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
