# Generated by Django 4.2.4 on 2023-09-14 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='billing_address',
        ),
        migrations.DeleteModel(
            name='shipping_address',
        ),
    ]
