# Generated by Django 4.2.4 on 2023-09-14 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_delete_billing_address_delete_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=10, null=True)),
                ('lname', models.CharField(blank=True, max_length=10, null=True)),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('shipping_address', models.CharField(blank=True, max_length=30, null=True)),
                ('shipping_address2', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh')], max_length=15, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=10)),
                ('lname', models.CharField(max_length=10)),
                ('billing_address', models.CharField(max_length=30)),
                ('billing_address2', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, choices=[('Bangladesh', 'Bangladesh')], max_length=15, null=True)),
                ('city', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=11)),
                ('cname', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
