# Generated by Django 4.2.4 on 2023-09-20 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_alter_billingaddress_user_alter_shippingaddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
