# Generated by Django 4.2.6 on 2023-10-09 08:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_order_code_alter_order_grand_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coupon', '0004_coupon_usage_limit_coupon_use_used_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='coupon_use',
            new_name='CouponUsage',
        ),
    ]
