# Generated by Django 4.2.6 on 2023-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_rename_coupon_use_couponusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=5),
            preserve_default=False,
        ),
    ]
