# Generated by Django 4.2.6 on 2023-10-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0006_couponusage_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusage',
            name='order',
        ),
    ]
