# Generated by Django 4.2.6 on 2023-10-09 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_couponusage_order_alter_couponusage_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponusage',
            name='order',
        ),
    ]
