# Generated by Django 4.2.4 on 2023-09-11 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
    ]
