# Generated by Django 4.2.4 on 2023-09-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='qty',
            field=models.CharField(max_length=3),
        ),
    ]
