# Generated by Django 4.2.4 on 2023-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_old_price_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cod',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Cash on Delivery'),
        ),
    ]
