# Generated by Django 4.2.5 on 2023-10-01 06:22

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
