# Generated by Django 4.2.4 on 2023-08-31 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='banner/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Banners',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(default='A Complete Store For Your Family', max_length=1000)),
                ('address', models.CharField(default='30/2, 30/3 SHAHJADPUR, PRAGATI SARANI, Dhaka 1212', max_length=1000)),
                ('email', models.EmailField(default='support@helpbazar.com', max_length=100)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('android', models.CharField(blank=True, max_length=1000, null=True)),
                ('iphone', models.CharField(blank=True, max_length=1000, null=True)),
                ('payment', models.ImageField(default='payment-method.png', upload_to='payment/')),
                ('mobile', models.CharField(default='01966172000', max_length=15)),
                ('working', models.CharField(default='Working 9:00 - 20:00', max_length=100)),
                ('support_title', models.CharField(default='24/7 Support Center', max_length=100)),
                ('facebook', models.CharField(default='facebook.com', max_length=255)),
                ('instagram', models.CharField(default='instagram.com', max_length=255)),
                ('twitter', models.CharField(default='twitter.com', max_length=255)),
                ('youtube', models.CharField(default='youtube.com', max_length=255)),
                ('linkedin', models.CharField(default='linkedin.com', max_length=255)),
                ('flash_news', models.CharField(default='Up to 15% discount on your first subscribe', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='assets/imgs/theme/logo.svg', upload_to='logo/')),
                ('contact', models.CharField(default='01773030088', max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Header Settings',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Flash News',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sliders', models.ImageField(upload_to='slider/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
