# Generated by Django 4.2.4 on 2023-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
    ]
