# Generated by Django 4.2.4 on 2023-09-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0002_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_value',
            name='min_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
