# Generated by Django 4.2.5 on 2023-10-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0003_alter_order_value_min_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='working',
            field=models.CharField(default='Working 9:00 - 16:00', max_length=100),
        ),
    ]
