# Generated by Django 4.2.6 on 2023-10-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('os_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='OS Info')),
                ('browser_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser Info')),
                ('device_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Info')),
                ('city', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'All Visitor',
            },
        ),
    ]
