# Generated by Django 4.2.4 on 2023-09-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productreview'),
        ('cart', '0002_remove_cart_products_cart_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(through='cart.CartItem', to='product.product'),
        ),
    ]
