# Generated by Django 4.2.4 on 2023-09-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_cart_min_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='min_value',
        ),
    ]
