# Generated by Django 4.2.4 on 2023-09-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_remove_order_products_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
