# Generated by Django 4.2.4 on 2023-09-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='BillingAddress',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
