# Generated by Django 4.2.4 on 2023-09-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_cartitem_order_remove_order_products_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
