# Generated by Django 4.2.4 on 2023-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0026_rename_status_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='grand_total',
        ),
    ]
