# Generated by Django 4.2.5 on 2023-10-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0031_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
