# Generated by Django 4.2.5 on 2023-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_remove_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('bKash', 'bKash'), ('Nagad', 'Nagad'), ('SSLCOMMERZE', 'SSLCOMMERZE')], max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
