# Generated by Django 4.2.4 on 2023-09-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_remove_profile_username_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
